spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empdb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
  main:
    banner-mode: off
server:
  port: 9090

mybatis:
  # 用于配置SQL语句的XML文件的位置
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn.tedu: trace
#开启Mp 输出到控制台的日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      # table-prefix: t_
      #配置逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
---
#生产
spring:
  profiles: dev
server:
  port: 8080

