spring:
  redis:
    host: 192.168.126.128
    port: 6379
    password: root
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0   #最小空闲连接
        max-wait: 100 #连接等待时间
